/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.course.registration.system.pkg1.pkg0;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Lau Kah Hou
 */
public class AddCourse extends javax.swing.JFrame {
    private List<String> s_info; //This list stores the student information of a student.
    private List<String> courseInfo; //This list stores the total available course in university.
    Student s1 = new Student();
    Course c1 = new Course();
    Bill b1 = new Bill();
    /**
     * Creates new form CourseReg
     */
    public AddCourse() {
        initComponents();
    }
    
    public AddCourse(List<String> studentInfo) {
        initComponents();
        try{
            s_info = studentInfo;
            this.id_lbl.setText(s_info.get(0));
            this.name_lbl.setText(s_info.get(2));
            c1.GetCourseInfo();
            this.courseInfo = c1.SetCourse();
            courseComboBox.setModel(new DefaultComboBoxModel(courseInfo.toArray()));
        }
        catch(Exception e){
            // TODO Auto-generated catch block
        }
    }

    /**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logout_btn = new javax.swing.JButton();
        bill_btn = new javax.swing.JButton();
        addCourse_btn = new javax.swing.JButton();
        manage_btn = new javax.swing.JButton();
        home_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        id_lbl = new javax.swing.JLabel();
        courseComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bill_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        add_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        logout_btn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        logout_btn.setText("Log Out");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        getContentPane().add(logout_btn);
        logout_btn.setBounds(0, 518, 170, 62);

        bill_btn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        bill_btn.setText("Display Bill");
        bill_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bill_btnActionPerformed(evt);
            }
        });
        getContentPane().add(bill_btn);
        bill_btn.setBounds(0, 450, 170, 62);

        addCourse_btn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        addCourse_btn.setText("Add Course");
        addCourse_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourse_btnActionPerformed(evt);
            }
        });
        getContentPane().add(addCourse_btn);
        addCourse_btn.setBounds(0, 382, 170, 62);

        manage_btn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        manage_btn.setText("Manage Profile");
        manage_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_btnActionPerformed(evt);
            }
        });
        getContentPane().add(manage_btn);
        manage_btn.setBounds(0, 314, 170, 62);

        home_btn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        home_btn.setText("Home");
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });
        getContentPane().add(home_btn);
        home_btn.setBounds(0, 246, 170, 62);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/course/registration/system/pkg1/pkg0/Images/john.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(21, 0, 113, 130);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Name: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 140, 44, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Student ID:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 190, 72, 17);

        name_lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name_lbl.setText("John Shimone Peter");
        getContentPane().add(name_lbl);
        name_lbl.setBounds(20, 160, 130, 17);

        id_lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id_lbl.setText("TPXXXXXXX");
        getContentPane().add(id_lbl);
        id_lbl.setBounds(20, 210, 80, 17);

        courseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        courseComboBox.setPreferredSize(null);
        getContentPane().add(courseComboBox);
        courseComboBox.setBounds(190, 150, 360, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Receipt ID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 380, 80, 20);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel6.setText("Add Course");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 10, 140, 33);
        getContentPane().add(bill_txt);
        bill_txt.setBounds(280, 410, 160, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Select course:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(320, 120, 100, 20);

        add_btn.setText("Add");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });
        getContentPane().add(add_btn);
        add_btn.setBounds(310, 450, 90, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        student_login f1 = new student_login();
        this.hide();
        f1.pack();
        f1.setSize(499, 699);
        f1.setLocationRelativeTo(null);
        f1.setVisible(true);
        f1.getContentPane().requestFocusInWindow();
    }//GEN-LAST:event_logout_btnActionPerformed

    private void bill_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bill_btnActionPerformed
        DisplayBill f1 = new DisplayBill(s_info);
        this.hide();
        f1.pack();
        f1.setSize(597, 610);
        f1.setLocationRelativeTo(null);
        f1.setVisible(true);
        f1.getContentPane().requestFocusInWindow();
    }//GEN-LAST:event_bill_btnActionPerformed

    private void addCourse_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourse_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCourse_btnActionPerformed

    private void manage_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_btnActionPerformed
        
        Profile f1 = new Profile(s_info);
        this.hide();
        f1.pack();
        f1.setSize(597, 610);
        f1.setLocationRelativeTo(null);
        f1.setVisible(true);
        f1.getContentPane().requestFocusInWindow();
        
    }//GEN-LAST:event_manage_btnActionPerformed

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        
        student_dashboard f1 = new student_dashboard(s_info);
        this.hide();
        f1.pack();
        f1.setSize(597, 610);
        f1.setLocationRelativeTo(null);
        f1.setVisible(true);
        f1.getContentPane().requestFocusInWindow();
    }//GEN-LAST:event_home_btnActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        b1.setCourse_title(courseComboBox.getSelectedItem().toString());
        b1.setStudent_id(s_info.get(0));
        b1.setBill_id(bill_txt.getText());
        
        if(c1.matchCourse(s_info, b1.getCourse_title(), b1.getBill_id()) == false){
            if(b1.ValidateBill() == true){
                s_info = c1.addCourse(s_info, b1.getCourse_title());
            }
            else{
                JOptionPane.showMessageDialog(null,"Invalid receipt id.");
            }
        }
    }//GEN-LAST:event_add_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourse_btn;
    private javax.swing.JButton add_btn;
    private javax.swing.JButton bill_btn;
    private javax.swing.JTextField bill_txt;
    private javax.swing.JComboBox<String> courseComboBox;
    private javax.swing.JButton home_btn;
    private javax.swing.JLabel id_lbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton manage_btn;
    private javax.swing.JLabel name_lbl;
    // End of variables declaration//GEN-END:variables
}
