/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.course.registration.system.pkg1.pkg0;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author lexin
 */
public class admin_login extends javax.swing.JFrame {

   
    public admin_login() {
        initComponents();
        GhostText g1 = new GhostText(adminid_txt, "e.g. AXXX");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        adminid_txt = new javax.swing.JTextField();
        pwd_txt = new javax.swing.JPasswordField();
        login_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Leelawadee", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Admin Login");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 90, 240, 80);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Admin ID:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(230, 200, 70, 21);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 250, 100, 21);

        adminid_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminid_txtActionPerformed(evt);
            }
        });
        getContentPane().add(adminid_txt);
        adminid_txt.setBounds(320, 200, 187, 22);
        getContentPane().add(pwd_txt);
        pwd_txt.setBounds(320, 250, 187, 22);

        login_btn.setText("Login");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        getContentPane().add(login_btn);
        login_btn.setBounds(260, 320, 120, 25);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/course/registration/system/pkg1/pkg0/Images/Lecturer.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 170, 155, 110);

        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn);
        back_btn.setBounds(400, 320, 120, 25);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/course/registration/system/pkg1/pkg0/Images/AdminInterface.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-60, -20, 880, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminid_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminid_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminid_txtActionPerformed

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        if(adminid_txt.getText().equals("") || pwd_txt.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill in your login details!");
        }   
        else{
            try{
                Admin s1 =  new Admin();
                s1.Adminid = adminid_txt.getText();
                s1.Pwd = pwd_txt.getText();
                s1.VerifyLogin(s1.Adminid, s1.Pwd, "Admin.txt");
                if(s1.found == true){
                    admin_page f1 = new admin_page();
                    this.hide();
                    f1.pack();
                    f1.setSize(960, 660);
                    f1.setLocationRelativeTo(null);
                    f1.setVisible(true);
                    f1.getContentPane().requestFocusInWindow();
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, "Invalid User ID or Password.");
            }
        }
    }//GEN-LAST:event_login_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        main_page f1 = new main_page();
        this.hide();
        f1.pack();
        f1.setSize(500, 730);
        f1.setLocationRelativeTo(null);
        f1.setVisible(true);
        f1.getContentPane().requestFocusInWindow();
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminid_txt;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton login_btn;
    private javax.swing.JPasswordField pwd_txt;
    // End of variables declaration//GEN-END:variables
}
