/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.course.registration.system.pkg1.pkg0;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static online.course.registration.system.pkg1.pkg0.User.x;


/**
 *
 * @author lexin
 */
public class Manage_profile extends javax.swing.JFrame {
    private List<String> studentList;
    //private List<String> studentInfo;
    List<String> tempList = new ArrayList();
    
    public Manage_profile() {
        initComponents();
        Admin a1 = new Admin();
        studentList = a1.getStudentList();
        studentComboBox.setModel(new DefaultComboBoxModel(studentList.toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        student_reg = new javax.swing.JButton();
        Adminhome_btn = new javax.swing.JButton();
        manageprofile_btn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        deglvl_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        contact_txt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pwd_txt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        update_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        studentComboBox = new javax.swing.JComboBox<>();
        search_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        student_reg.setText("Student Registration");
        student_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_regActionPerformed(evt);
            }
        });
        getContentPane().add(student_reg);
        student_reg.setBounds(0, 420, 170, 53);

        Adminhome_btn.setText("Home");
        Adminhome_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adminhome_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Adminhome_btn);
        Adminhome_btn.setBounds(0, 350, 170, 53);

        manageprofile_btn.setText("Manage Profile");
        manageprofile_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageprofile_btnActionPerformed(evt);
            }
        });
        getContentPane().add(manageprofile_btn);
        manageprofile_btn.setBounds(0, 490, 170, 48);

        jButton4.setText("Logout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(0, 550, 170, 46);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Name: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(756, 120, 44, 17);

        name_txt.setEditable(false);
        name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txtActionPerformed(evt);
            }
        });
        getContentPane().add(name_txt);
        name_txt.setBounds(743, 137, 188, 32);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Student ID:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(743, 187, 72, 17);

        id_txt.setEditable(false);
        getContentPane().add(id_txt);
        id_txt.setBounds(743, 211, 188, 32);

        deglvl_txt.setEditable(false);
        getContentPane().add(deglvl_txt);
        deglvl_txt.setBounds(753, 285, 182, 32);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Degree Level:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(753, 261, 84, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Contact Number:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(753, 335, 107, 17);
        getContentPane().add(contact_txt);
        contact_txt.setBounds(752, 359, 179, 32);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Email ID:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(752, 409, 54, 17);
        getContentPane().add(pwd_txt);
        pwd_txt.setBounds(750, 513, 181, 32);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Password:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(750, 489, 63, 17);

        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        getContentPane().add(update_btn);
        update_btn.setBounds(800, 560, 90, 23);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Student Profile Management");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 30, 257, 73);
        getContentPane().add(email_txt);
        email_txt.setBounds(752, 439, 179, 32);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/course/registration/system/pkg1/pkg0/Images/Lecturer.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 0, 180, 200);

        studentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        studentComboBox.setPreferredSize(null);
        studentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(studentComboBox);
        studentComboBox.setBounds(210, 150, 380, 40);

        search_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/course/registration/system/pkg1/pkg0/Images/icons8_search_32px_2.png"))); // NOI18N
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        getContentPane().add(search_btn);
        search_btn.setBounds(600, 150, 40, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/course/registration/system/pkg1/pkg0/Images/managecourse.PNG"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, -90, 990, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void student_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_regActionPerformed
        student_register f1 = new student_register();
        this.hide();
        f1.pack();
        f1.setSize(1000, 720);
        f1.setLocationRelativeTo(null);
        f1.setVisible(true);
        f1.getContentPane().requestFocusInWindow();
    }//GEN-LAST:event_student_regActionPerformed

    private void Adminhome_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adminhome_btnActionPerformed
        admin_page f1 = new admin_page();
        this.hide();
        f1.pack();
        f1.setSize(960, 660);
        f1.setLocationRelativeTo(null);
        f1.setVisible(true);
        f1.getContentPane().requestFocusInWindow();
    }//GEN-LAST:event_Adminhome_btnActionPerformed

    private void manageprofile_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageprofile_btnActionPerformed
        Manage_profile f1 = new Manage_profile();
        this.hide();
        f1.pack();
        f1.setSize(1000, 650);
        f1.setLocationRelativeTo(null);
        f1.setVisible(true);
        f1.getContentPane().requestFocusInWindow();
    }//GEN-LAST:event_manageprofile_btnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        admin_login f1 = new admin_login();
        this.hide();
        f1.pack();
        f1.setSize(699, 500);
        f1.setLocationRelativeTo(null);
        f1.setVisible(true);
        f1.getContentPane().requestFocusInWindow();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txtActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed

        tempList.set(4,contact_txt.getText());
        tempList.set(5,email_txt.getText());
        tempList.set(1,pwd_txt.getText());
        //Write the file from the list.
        EditFile f = new EditFile();
        f.changeALineInATextFile("Student.txt",f.arrayListToString(tempList),tempList.get(0));
        JOptionPane.showMessageDialog(null,"Update Successful!");
    }//GEN-LAST:event_update_btnActionPerformed

    private void studentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_studentComboBoxActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        //Save the changes in a list.
        List<String> studentInfo = new ArrayList();
        try{
            x = new Scanner(new BufferedReader (new FileReader("Student.txt")));
            x.useDelimiter("[,\n]"); //String pattern in the textfile
            while (x.hasNext()){
                String line = x.nextLine();
                if (line.isEmpty()){
                    continue;
                }
                else if(line.contains(studentComboBox.getSelectedItem().toString())){
                    String[] tokens = line.split(",");
                    for (String token : tokens){
                        if (token.isEmpty())
                            continue;
                        // do whatever processing for each token
                        else{
                            studentInfo.add(token);
                        }
                    }
                }
            }
            tempList = studentInfo;
        }    
        catch(FileNotFoundException e){
            JOptionPane.showMessageDialog(null,e);
        } 
        name_txt.setText(studentInfo.get(2));
        id_txt.setText(studentInfo.get(0));
        deglvl_txt.setText(studentInfo.get(3));
        contact_txt.setText(studentInfo.get(4));
        email_txt.setText(studentInfo.get(5));
        pwd_txt.setText(studentInfo.get(1));
    }//GEN-LAST:event_search_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adminhome_btn;
    private javax.swing.JTextField contact_txt;
    private javax.swing.JTextField deglvl_txt;
    private javax.swing.JTextField email_txt;
    private javax.swing.JTextField id_txt;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton manageprofile_btn;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField pwd_txt;
    private javax.swing.JButton search_btn;
    private javax.swing.JComboBox<String> studentComboBox;
    private javax.swing.JButton student_reg;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
