/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.course.registration.system.pkg1.pkg0;
import javax.swing.JOptionPane;

/**
 *
 * @author Lau Kah Hou
 */
public class student_login extends javax.swing.JFrame {

    /**
     * Creates new form Login_Page
     */
    public student_login() {
        initComponents();
        GhostText g1 = new GhostText(studentid_txt, "e.g. TP012345");
    }

    /**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        studentid_txt = new javax.swing.JTextField();
        pwd_txt = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        login_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Pristina", 1, 48)); // NOI18N
        jLabel1.setText("Student Portal");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 130, 290, 110);

        studentid_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentid_txtActionPerformed(evt);
            }
        });
        getContentPane().add(studentid_txt);
        studentid_txt.setBounds(210, 270, 187, 22);
        getContentPane().add(pwd_txt);
        pwd_txt.setBounds(210, 320, 187, 22);

        jLabel2.setText("Student ID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 270, 70, 16);

        jLabel3.setText("Password:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 320, 70, 16);

        login_btn.setText("Login");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        getContentPane().add(login_btn);
        login_btn.setBounds(140, 380, 120, 25);

        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn);
        back_btn.setBounds(280, 380, 120, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/course/registration/system/pkg1/pkg0/Images/GIF Background.gif"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 500, 700);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        
        Student s1 =  new Student();
        s1.setUser_id(studentid_txt.getText());
        s1.setPwd(pwd_txt.getText());
        s1.setFile_path("Student.txt");
        if(s1.getUser_id().equals("") || s1.getPwd().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill in your login details!");
        }
        else{
            s1.VerifyLogin(s1.getUser_id(), s1.getPwd(),s1.getFile_path());
            if(s1.found == true){ 
                s1.SaveInfo(s1.user_id, s1.pwd);
                student_dashboard f1 = new student_dashboard(s1.studentInfo);
                this.hide();
                f1.pack();
                f1.setSize(597, 610);
                f1.setLocationRelativeTo(null);
                f1.setVisible(true);
                f1.getContentPane().requestFocusInWindow();
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid User ID or Password.");
            }
        }
    }//GEN-LAST:event_login_btnActionPerformed

    private void studentid_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentid_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentid_txtActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        main_page f1 = new main_page();
        this.hide();
        f1.pack();
        f1.setSize(500, 730);
        f1.setLocationRelativeTo(null);
        f1.setVisible(true);
        f1.getContentPane().requestFocusInWindow();
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton login_btn;
    private javax.swing.JPasswordField pwd_txt;
    private javax.swing.JTextField studentid_txt;
    // End of variables declaration//GEN-END:variables
}
