/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.course.registration.system.pkg1.pkg0;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;

/**
 *
 * @author Lau Kah Hou
 */
public class student_dashboard extends javax.swing.JFrame {
    private List<String> s_info;
    private List<String> courseInfo;
    DefaultListModel course;//Model
    final JPopupMenu pop = new JPopupMenu();
    String row = "";//This is for adding the specific information for the course
    Course c1 = new Course();
    
    public student_dashboard() {
        initComponents();
    }
                
    public student_dashboard(List<String> studentInfo) {
        initComponents();
        try{
            
            s_info = studentInfo;
            this.id_lbl.setText(s_info.get(0));
            this.name_lbl.setText(s_info.get(2));
            course = new DefaultListModel();
            for (int i = 6; i < s_info.size() ; i++){
                course.addElement(s_info.get(i));
            }
            reg_course_list.setModel(course);
            addPopup();
            c1.GetCourseInfo();
            this.courseInfo = c1.SetCourse();
            courseComboBox.setModel(new DefaultComboBoxModel(courseInfo.toArray()));      
        }
        catch(Exception e){
            // TODO Auto-generated catch block
        }
    }
    
    //https://www.youtube.com/watch?v=vTUcQyjt3OM
    public void addPopup(){
        JMenuItem show = new JMenuItem("Show details");
        JMenuItem drop = new JMenuItem("Drop course");
        
        //Add items to Popup Menu
        pop.add(show);
        pop.add(drop);
        
        //Events
        show.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e ){
                c1.generateDetails(courseComboBox.getSelectedItem().toString(),"listBox");
            }
        });
        
        drop.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e ){
                for (String s : s_info)
                {
                    if(reg_course_list.getSelectedValue().equals(s)){
                        s_info.remove(s);
                        break;
                    }
                }
                EditFile f = new EditFile();
                f.changeALineInATextFile("Student.txt",f.arrayListToString(s_info),s_info.get(0));
                student_dashboard.this.hide();
                student_dashboard f1 = new student_dashboard(s_info);
                f1.pack();
                f1.setSize(597, 610);
                f1.setLocationRelativeTo(null);
                f1.setVisible(true);
                f1.getContentPane().requestFocusInWindow();
            }
        });
    }

    /**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        logout_btn = new javax.swing.JButton();
        bill_btn = new javax.swing.JButton();
        addCourse_btn = new javax.swing.JButton();
        manage_btn = new javax.swing.JButton();
        home_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reg_course_list = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        id_lbl = new javax.swing.JLabel();
        search_btn = new javax.swing.JButton();
        instruction_lbl = new javax.swing.JLabel();
        courseComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        logout_btn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        logout_btn.setText("Log Out");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        getContentPane().add(logout_btn);
        logout_btn.setBounds(0, 518, 170, 62);

        bill_btn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        bill_btn.setText("Display Bill");
        bill_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bill_btnActionPerformed(evt);
            }
        });
        getContentPane().add(bill_btn);
        bill_btn.setBounds(0, 450, 170, 62);

        addCourse_btn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        addCourse_btn.setText("Add Course");
        addCourse_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourse_btnActionPerformed(evt);
            }
        });
        getContentPane().add(addCourse_btn);
        addCourse_btn.setBounds(0, 382, 170, 62);

        manage_btn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        manage_btn.setText("Manage Profile");
        manage_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_btnActionPerformed(evt);
            }
        });
        getContentPane().add(manage_btn);
        manage_btn.setBounds(0, 314, 170, 62);

        home_btn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        home_btn.setText("Home");
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });
        getContentPane().add(home_btn);
        home_btn.setBounds(0, 246, 170, 62);

        reg_course_list.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        reg_course_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reg_course_listMouseClicked(evt);
            }
        });
        reg_course_list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                reg_course_listValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(reg_course_list);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 100, 420, 480);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel2.setText("Registered Course");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 50, 195, 33);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/course/registration/system/pkg1/pkg0/Images/john.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(21, 0, 113, 130);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Name: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 140, 44, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Student ID:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 190, 72, 17);

        name_lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name_lbl.setText("John Shimone Peter");
        getContentPane().add(name_lbl);
        name_lbl.setBounds(20, 160, 130, 17);

        id_lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id_lbl.setText("TPXXXXXXX");
        getContentPane().add(id_lbl);
        id_lbl.setBounds(20, 210, 80, 17);

        search_btn.setBackground(new java.awt.Color(255, 255, 255));
        search_btn.setForeground(new java.awt.Color(255, 255, 255));
        search_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online/course/registration/system/pkg1/pkg0/Images/icons8_search_32px_2.png"))); // NOI18N
        search_btn.setRolloverEnabled(false);
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        getContentPane().add(search_btn);
        search_btn.setBounds(550, 20, 30, 30);

        instruction_lbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instruction_lbl.setText("#Select the course below and right click it for more options.");
        getContentPane().add(instruction_lbl);
        instruction_lbl.setBounds(170, 80, 380, 17);

        courseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        courseComboBox.setPreferredSize(null);
        courseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(courseComboBox);
        courseComboBox.setBounds(170, 20, 380, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Search course:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 0, 100, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        student_login f1 = new student_login();
        this.hide();
        f1.pack();
        f1.setSize(499, 699);
        f1.setLocationRelativeTo(null);
        f1.setVisible(true);
        f1.getContentPane().requestFocusInWindow();
    }//GEN-LAST:event_logout_btnActionPerformed

    private void bill_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bill_btnActionPerformed
        DisplayBill f1 = new DisplayBill(s_info);
        this.hide();
        f1.pack();
        f1.setSize(597, 610);
        f1.setLocationRelativeTo(null);
        f1.setVisible(true);
        f1.getContentPane().requestFocusInWindow();
    }//GEN-LAST:event_bill_btnActionPerformed

    private void addCourse_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourse_btnActionPerformed

        AddCourse f1 = new AddCourse(s_info);
        this.hide();
        f1.pack();
        f1.setSize(597, 610);
        f1.setLocationRelativeTo(null);
        f1.setVisible(true);
        f1.getContentPane().requestFocusInWindow();
    }//GEN-LAST:event_addCourse_btnActionPerformed

    private void manage_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_btnActionPerformed

        Profile f1 = new Profile(s_info);
        this.hide();
        f1.pack();
        f1.setSize(597, 610);
        f1.setLocationRelativeTo(null);
        f1.setVisible(true);
        f1.getContentPane().requestFocusInWindow();
    }//GEN-LAST:event_manage_btnActionPerformed

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_home_btnActionPerformed

    private void reg_course_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_course_listMouseClicked
        //This code is for adjusting the position of the options menu when right click is done by user.

        if(SwingUtilities.isRightMouseButton(evt) && reg_course_list.locationToIndex(evt.getPoint()) == reg_course_list.getSelectedIndex()){
            //Make sure sth is selected
            if( ! reg_course_list.isSelectionEmpty()){
                pop.show(reg_course_list,evt.getX(),evt.getY());
            }
        }
    }//GEN-LAST:event_reg_course_listMouseClicked

    private void reg_course_listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_reg_course_listValueChanged
        // TODO add your handling code here:
        row = reg_course_list.getSelectedValue();
    }//GEN-LAST:event_reg_course_listValueChanged

    private void courseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseComboBoxActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        //for (int i = 0; i < courseComboBox.getItemCount(); i++){
        //String courseCh = courseComboBox.getSelectedItem().toString();
        c1.generateDetails(courseComboBox.getSelectedItem().toString(),"search");
    }//GEN-LAST:event_search_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student_dashboard().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourse_btn;
    private javax.swing.JButton bill_btn;
    private javax.swing.JComboBox<String> courseComboBox;
    private javax.swing.JButton home_btn;
    private javax.swing.JLabel id_lbl;
    private javax.swing.JLabel instruction_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton manage_btn;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JList<String> reg_course_list;
    private javax.swing.JButton search_btn;
    // End of variables declaration//GEN-END:variables
}
