# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WalletMelon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WalletMelon
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Macaw', "0.9.5"

end
